# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:boot-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      BOOT_JVM_OPTIONS: -Xmx3g -client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      - run: boot tests-cljs
      - run: boot test

      - save_cache:
          paths:
            - "~/bin"
            - "~/.m2"
            - "~/.boot/cache/bin"
            - "~/.boot/cache/lib"
          key: v1-dependencies-{{ checksum "build.boot" }}

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              boot build-jar push-snapshot
            fi
